/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-11-11 04:39:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import volunteer.vo.ListVO;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/04_MiddelProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Volunteer/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1667995182576L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("volunteer.vo.ListVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<ListVO> list = (List<ListVO>) request.getAttribute("list");

String msg = session.getAttribute("msg") == null ? "" : (String) session.getAttribute("msg");
session.removeAttribute("msg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>온(ON:溫)</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("div {\r\n");
      out.write("	border: 1px solid black\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#filter {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#listArea {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ListAreaTable {\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<div class=\"col-sm-12 text-center\">\r\n");
      out.write("		<h1>봉사 프로그램 목록</h1>\r\n");
      out.write("\r\n");
      out.write("		<!-- 필터 시작 -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<h2 id=\"filter\">필터</h2>\r\n");
      out.write("			<table class=\"table\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>지역</th>\r\n");
      out.write("						<th>유형</th>\r\n");
      out.write("						<th>날짜</th>\r\n");
      out.write("						<th>대상</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"locationFilter\">\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item btn active\">전체</a>\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item btn\">Second item</a>\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item btn\">Third item</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"categoryFilter\">\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item active\">전체</a>\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item\">Second item</a>\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item\">Third item</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"dateFilter\">\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item active\">전체</a>\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item\">Second item</a>\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item\">Third item</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"targetFilter\">\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item active\">전체</a>\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item\">Second item</a>\r\n");
      out.write("							  <a href=\"#\" class=\"list-group-item\">Third item</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 필터 끝 -->\r\n");
      out.write("\r\n");
      out.write("		<hr>\r\n");
      out.write("		\r\n");
      out.write("		<!-- 리스트 시작 -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			");

					int size = list.size();
				if (size > 0) {
					for (int i = 0; i < size; i++) {
				
      out.write("\r\n");
      out.write("			<div class=\"list-group\">\r\n");
      out.write("				<a href=\"showDetail.do?volId=");
      out.print( (list.get(i).getVolId()) );
      out.write("\" class=\"list-group-item\">\r\n");
      out.write("			        <h1>[");
      out.print((list.get(i).getVolCtId()));
      out.write(']');
      out.print((list.get(i).getVolTitle()));
      out.write("</h1>\r\n");
      out.write("					[모집 기간]   ");
      out.print((list.get(i).getStartDate()));
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print((list.get(i).getEndDate()));
      out.write(" <br>\r\n");
      out.write("					[모집 시간]   ");
      out.print((list.get(i).getStartTime()));
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print((list.get(i).getEndTime()));
      out.write(" <br>\r\n");
      out.write("					[신청 인원]   ");
      out.print((list.get(i).getTotal()));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print((list.get(i).getPersonnel()));
      out.write(" <br> \r\n");
      out.write("					[봉사 장소]   ");
      out.print((list.get(i).getLocation()));
      out.write(" <br>\r\n");
      out.write("					[모집 상태]   ");
      out.print((list.get(i).getStatus()));
      out.write(" <br>\r\n");
      out.write("					[봉사 대상]   ");
      out.print((list.get(i).getTarget()));
      out.write(" <br>\r\n");
      out.write("					[자격 요건]   ");
      out.print((list.get(i).getQualification()));
      out.write("\r\n");
      out.write("					<i class=\"bi-heart\" style=\"font-size:3rem; color: red; cursor: pointer;\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

					}
				} else {
				
      out.write("\r\n");
      out.write("			조회된 데이터가 없습니다.\r\n");
      out.write("			");

					}
				
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 리스트 끝 -->\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("        var i = 0;\r\n");
      out.write("        $('i').on('click',function(){\r\n");
      out.write("            if(i==0){\r\n");
      out.write("                $(this).attr('class','bi-heart-fill');\r\n");
      out.write("                i++;\r\n");
      out.write("            }else if(i==1){\r\n");
      out.write("                $(this).attr('class','bi-heart');\r\n");
      out.write("                i--;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("       	var active = 'list-group-item active';\r\n");
      out.write("       	var inactive = 'list-group-item';\r\n");
      out.write("//        	var lfSize = $('.locationFilter').children().length;\r\n");
      out.write("		\r\n");
      out.write("		// $(event.target)\r\n");
      out.write("// 		$(\"body\").click(function(event){\r\n");
      out.write("// 			if(event.target)\r\n");
      out.write("// 		    console.log(\"무엇을 클릭했을 까요? \", event.target.nodeName);\r\n");
      out.write("// 		})\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("        $('.locationFilter a:nth-of-type(' + 1 + ')').on('click', function(){\r\n");
      out.write("    		$('.locationFilter a').attr('class', inactive);\r\n");
      out.write("    		$('.locationFilter a:nth-of-type(' + 1 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("        $('.locationFilter a:nth-of-type(' + 2 + ')').on('click', function(){\r\n");
      out.write("    		$('.locationFilter a').attr('class', inactive);\r\n");
      out.write("    		$('.locationFilter a:nth-of-type(' + 2 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("        $('.locationFilter a:nth-of-type(' + 3 + ')').on('click', function(){\r\n");
      out.write("    		$('.locationFilter a').attr('class', inactive);\r\n");
      out.write("    		$('.locationFilter a:nth-of-type(' + 3 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        $('.categoryFilter a:nth-of-type(' + 1 + ')').on('click', function(){\r\n");
      out.write("    		$('.categoryFilter a').attr('class', inactive);\r\n");
      out.write("    		$('.categoryFilter a:nth-of-type(' + 1 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("        $('.categoryFilter a:nth-of-type(' + 2 + ')').on('click', function(){\r\n");
      out.write("    		$('.categoryFilter a').attr('class', inactive);\r\n");
      out.write("    		$('.categoryFilter a:nth-of-type(' + 2 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("        $('.categoryFilter a:nth-of-type(' + 3 + ')').on('click', function(){\r\n");
      out.write("    		$('.categoryFilter a').attr('class', inactive);\r\n");
      out.write("    		$('.categoryFilter a:nth-of-type(' + 3 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        $('.dateFilter a:nth-of-type(' + 1 + ')').on('click', function(){\r\n");
      out.write("    		$('.dateFilter a').attr('class', inactive);\r\n");
      out.write("    		$('.dateFilter a:nth-of-type(' + 1 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("        $('.dateFilter a:nth-of-type(' + 2 + ')').on('click', function(){\r\n");
      out.write("    		$('.dateFilter a').attr('class', inactive);\r\n");
      out.write("    		$('.dateFilter a:nth-of-type(' + 2 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("        $('.dateFilter a:nth-of-type(' + 3 + ')').on('click', function(){\r\n");
      out.write("    		$('.dateFilter a').attr('class', inactive);\r\n");
      out.write("    		$('.dateFilter a:nth-of-type(' + 3 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        $('.targetFilter a:nth-of-type(' + 1 + ')').on('click', function(){\r\n");
      out.write("    		$('.targetFilter a').attr('class', inactive);\r\n");
      out.write("			$('.targetFilter a:nth-of-type(' + 1 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("        $('.targetFilter a:nth-of-type(' + 2 + ')').on('click', function(){\r\n");
      out.write("    		$('.targetFilter a').attr('class', inactive);\r\n");
      out.write("			$('.targetFilter a:nth-of-type(' + 2 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("        $('.targetFilter a:nth-of-type(' + 3 + ')').on('click', function(){\r\n");
      out.write("    		$('.targetFilter a').attr('class', inactive);\r\n");
      out.write("			$('.targetFilter a:nth-of-type(' + 3 + ')').attr('class', active);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
